---
test:
- testname: provision-vm
  vm_name: rdr-miq-test-1
  key_pair_name: miq-pvs
  public_network_name: public-192_168_165_88-29-VLAN_2039
  power_network_name: miq-net
  image_name: '7100-05-05'
  sys_type: s922
  volume_name: rdr-miq-volume-1
