:ems:
  :ems_ibm_cloud_power_virtual_servers:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
        :power:
          :critical:
          - IBM_CLOUD_POWER_VIRTUAL_SERVERS_instance_power_on
          - IBM_CLOUD_POWER_VIRTUAL_SERVERS_instance_power_off
:ems_refresh:
  :ibm_cloud_power_virtual_servers:
    :storage_types:
    - :description: Tier 1
      :state: active
      :type: tier1
    - :description: Tier 3
      :state: active
      :type: tier3
    - :description: SSD
      :state: active
      :type: ssd-legacy
    - :description: Standard
      :state: active
      :type: standard-legacy
:http_proxy:
  :ibm_cloud_power_virtual_servers:
    :host:
    :password:
    :port:
    :user:
:log:
  :level_ibm_cloud: info
:workers:
  :worker_base:
    :event_catcher:
      :event_catcher_ibm_cloud_power_virtual_servers:
        :poll: 20.seconds
    :queue_worker_base:
      :ems_refresh_worker:
        :ems_refresh_worker_ibm_cloud_power_virtual_servers: {}
